import { Router } from "express";
import { isAuthenticated } from "../../middleware/auth.middlewae";
import commentService from "./comment.service";
const router=Router({mergeParams:true});
router.post("{/:id}",isAuthenticated(),commentService.create);
router.get("/:id",isAuthenticated(),commentService.getSpcific);
router.delete("/:id",isAuthenticated(),commentService.HardDeleteComment);
router.patch("/:id",isAuthenticated(),commentService.updateComment);
router.patch("/add-reaction/:id",isAuthenticated(),commentService.addReaction);
router.patch("/freeze/:id",isAuthenticated(),commentService.freezeComment);
export default router;